apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker-node
                operator: Exists
      containers:
      - name: application
        image: sudeepk12/application:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: application-service-new
spec:
  type: NodePort
  selector:
    app: application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30100
